# PATHS
wav_path: '../data/wavs/SPEECOMCO/'
data_path: './data/'
embedding_path: './data/embeddings/xvec/'
model_path: './models/'

train_set_file: './data/TRAIN_LEC_SEGAUG_C2SI_98_XVEC.csv'            #'./data/TRAINING.txt'
validation_set_file: './data/VALIDATION_LEC_SEGAUG_C2SI_10_XVEC.csv'
test_set_file: './data/TEST_DAP_UNSEGMENTED_XVEC.csv'



# TRAINING PARAMETERS
sampling_rate: 16000
batch_size: 8
learning_rate: 0.001
epochs: 20
dropout: 0.2



# MODEL PARAMETERS

first_layer: 512
second_layer: 128
third_layer: 64



# Types of embeddings supported: 'ecapa_tdnn' or 'x-vector'
# ecapa_tdnn: dim = 192 (change first_layer dim)
# x-vector: dim = 512   (change first_layer dim)
embedding_type: x-vector
