# PATHS
wav_path: '../data/wavs/'
embedding_path: '../data/embeddings/'

# PARAMETERS
sampling_rate: 16000
batch_size: 16
learning_rate: 0.001

# Types of embeddings supported: 'ecapa_tdnn' or 'x-vector'
# ecapa_tdnn: dim = 192
# x-vector: dim = 512
embedding_type: x-vector
